/* Shared demo registry.
 *
 * gallery.html, pipeline.html and viewer.html all read from this one file, so
 * adding a scene is a single entry here rather than three parallel edits. Keep
 * the shapes below stable; the pages assume them.
 *
 * A demo needs:
 *   id, title, tagline, facts[]      — identity and the headline numbers
 *   stills[]                          — gallery entries (file, name, what, why, alt)
 *   viewer{}                          — glTF variants + home camera, for viewer.html
 *   pipeline{nodes[], edges[]}        — the diagram, incl. hover text and source links
 *   run                               — the command that reproduces it
 *
 * Node kinds map to colours: env | code | data | stage | out | view.
 * Node `src` is [path, symbol]; the symbol is searched in the file at click
 * time rather than stored as a line number, so links survive edits.
 */
window.DEMOS = [

/* ------------------------------------------------------------------ CITY -- */
{
  id: 'city',
  title: 'Procedural city',
  tagline: 'A three.js city plan rebuilt in Blender and path traced in Cycles — same constants, so what changes between them is the renderer, not the city.',
  run: 'blender --background --python blender/build_city.py -- --preset noon',
  facts: [
    ['plots', '84'], ['objects', '121'], ['GN instances', '167'],
    ['samples', '96'], ['render', '4–6 s'],
  ],
  stills: [
    { file: 'renders/city_noon.png', name: 'noon · 60° sun',
      what: 'Global illumination, soft shadows, and glass that actually refracts.',
      why: '<b>Not possible in three.js:</b> light bounces. Facades pick up colour from their surroundings, and the sun\'s angular diameter gives shadows a real penumbra.',
      alt: 'Daylight aerial view of a procedural city: glass and concrete towers on a block grid, a meandering river west crossed by two bridges, and a green park with a pond east.' },
    { file: 'renders/city_dusk.png', name: 'dusk · 4° sun',
      what: 'Low sun through a physically-based sky, with depth of field.',
      why: '<b>Not possible in three.js:</b> the sky model is live, not a baked environment map — drop the sun to 4° and the long atmospheric path strips the blue out by itself.',
      alt: 'The city at dusk under a deep blue sky, warm light catching the tops of the two tallest towers, window grids beginning to glow.' },
    { file: 'renders/city_night.png', name: 'night · sun below horizon',
      what: 'The windows are the light source.',
      why: '<b>The clearest thing three.js cannot do.</b> An emissive material in a rasteriser looks bright but illuminates nothing. Here the lit panes light the towers opposite and the street below.',
      alt: 'The city at night, almost entirely dark except two towers whose scattered lit windows glow and cast light onto the buildings and ground below.' },
    { file: 'renders/city_tiltshift.png', name: 'tiltshift · f/1.4',
      what: 'A real aperture, not a blur filter.',
      why: '<b>Not possible in three.js:</b> the defocus comes from tracing rays through a physical lens, so it falls off correctly with distance.',
      alt: 'Steep near-overhead view of the whole city rendered to look like a miniature model, block grid and bridges visible, frame edges softly out of focus.' },
  ],
  viewer: {
    variants: [
      { label: 'Day',   file: 'renders/city_day.glb',   night: false },
      { label: 'Night', file: 'renders/city_night.glb', night: true  },
    ],
    home: { pos: [215, 135, 235], target: [0, 14, 0] },
    sky: { day: { elev: 34, azim: 128 }, night: { elev: -4, azim: 128 } },
    note: 'Emissive windows glow here but light nothing — that is the light transport left behind in Cycles.',
  },
  pipeline: {
    nodes: [
      { id:'shell', x:40, y:36, w:250, h:70, kind:'env', lab:'shell.nix', sub:'pinned nixpkgs',
        t:'The lock', d:'Pins nixpkgs by revision and hash. Resolves to exactly the Blender already in the store, so entering the shell fetches 2.62 MiB of stdenv and no Blender. An earlier pin to the registry tarball looked right but resolved to a different store path — it would have re-downloaded 851 MiB.',
        src:['shell.nix','nixpkgs ? builtins.fetchTarball'] },
      { id:'gc', x:40, y:140, w:250, h:64, kind:'env', lab:'.nix-gcroot-blender', sub:'GC root',
        t:'Garbage-collection root', d:'A symlink into /nix/store that stops nix-collect-garbage deleting the closure. This machine runs near-full and GC is a live reclaim option. A GC root under /tmp does not count — /tmp gets cleaned.',
        src:['shell.nix','GC root'] },
      { id:'blender', x:380, y:36, w:250, h:70, kind:'env', lab:'Blender 5.2.0 LTS', sub:'851 MiB, 0 built',
        t:'The renderer', d:'Installed entirely from cache.nixos.org — 189 paths, nothing compiled. Five 5.x API changes broke this build; each was found by probing the runtime, never by recall.',
        src:['shell.nix','pkgs.blender'] },
      { id:'gpu', x:720, y:36, w:280, h:70, kind:'env', lab:'Cycles · METAL', sub:'M2 Max, 38 GPU cores',
        t:'GPU path tracing', d:'The main open risk: nixpkgs could have compiled Cycles CPU-only on Darwin. It did not. Detected at runtime with a clean CPU fallback. This is why a frame takes seconds, not minutes.',
        src:['blender/city/render.py','def configure_device'] },

      { id:'cli', x:40, y:262, w:250, h:76, kind:'code', lab:'CLI arguments', sub:'--preset --seed --samples',
        t:'Command line', d:'Parsed from after the "--" separator; everything before it belongs to Blender. --no-render builds the scene and stops, a fast structural check needing no rendering.',
        src:['blender/build_city.py','def _parse_args'] },
      { id:'entry', x:380, y:262, w:250, h:76, kind:'code', lab:'build_city.py', sub:'stage order · ctx',
        t:'Orchestrator', d:'Clears the scene, builds the ctx every stage receives, runs seven stages in order. Each is wrapped so an exception names the failing stage — which is how the black-frame bugs were localised instead of guessed at.',
        src:['blender/build_city.py','def main'] },
      { id:'layout', x:720, y:262, w:280, h:76, kind:'code', lab:'city/layout.py', sub:'the frozen contract',
        t:'Single source of truth', d:'Constants ported from buildings.html, tower_plots() resolving all 84 footprints, and the preset schema. Imports no bpy, so it runs under plain python3 and can be diffed against the three.js constants.',
        src:['blender/city/layout.py','PITCH: float'] },

      { id:'mat', x:380, y:400, w:250, h:66, kind:'stage', lab:'1 · materials', sub:'13 node graphs',
        t:'Materials', d:'Every surface is a node graph — no image files. Glass is a real Principled BSDF with transmission. The lane markings, a canvas texture in the three.js version, are procedural here.',
        src:['blender/city/materials.py','def build_materials'] },
      { id:'terr', x:380, y:486, w:250, h:66, kind:'stage', lab:'2 · terrain', sub:'river · park · streets',
        t:'Terrain', d:'Ground, the meandering river sampled along its sine centreline, park and pond, street grid with kerbed blocks, and bridges placed at river_centre(z).',
        src:['blender/city/terrain.py','def build_terrain'] },
      { id:'bld', x:380, y:572, w:250, h:66, kind:'stage', lab:'3 · buildings', sub:'84 plots → 121 objects',
        t:'Towers', d:'Podium/shaft/crown above 30 units. Shafts share one unit mesh and differ by scale. Window grids are procedural, driven from world position so a window cell stays the same real size on every tower.',
        src:['blender/city/buildings.py','def build_buildings'] },
      { id:'scat', x:380, y:658, w:250, h:66, kind:'stage', lab:'4 · scatter', sub:'Geometry Nodes',
        t:'Procedural scatter', d:'The three.js version hand-places 110 trees. This is a node graph: distribute on the lawn, mask the pond, randomise rotation and scale. Change the seed and the park repopulates.',
        src:['blender/city/scatter.py','def build_scatter'] },
      { id:'light', x:380, y:744, w:250, h:66, kind:'stage', lab:'5 · lighting', sub:'sky · sun · atmosphere',
        t:'Lighting', d:'Physically-based sky driving the actual light, a sun kept in agreement with it, and a bounded volumetric atmosphere. In 5.x the NISHITA sky type no longer exists.',
        src:['blender/city/lighting.py','def build_lighting'] },
      { id:'cam', x:380, y:830, w:250, h:66, kind:'stage', lab:'6 · camera', sub:'framing · DOF',
        t:'Camera', d:'Positioned and aimed from the preset, depth of field from a real f-stop. Focus distance must match camera-to-target or the plane sits in empty air — the original tiltshift preset focused at 260 with the city at 640.',
        src:['blender/city/camera.py','def build_camera'] },
      { id:'conf', x:380, y:916, w:250, h:66, kind:'stage', lab:'7 · render.configure', sub:'device · samples',
        t:'Render settings', d:'Detects the backend, sets samples and resolution, enables denoising, picks AgX and wires the glare compositor. Dynamic enums here report [NONE] under static introspection while assigning fine — gating on that list stranded the render on CPU.',
        src:['blender/city/render.py','def configure(ctx)'] },

      { id:'plots', x:720, y:572, w:280, h:66, kind:'data', lab:'84 plots', sub:'x z w d h is_glass',
        t:'Resolved footprints', d:'tower_plots(seed) does the layout maths once. Verified: z-range 1.2 to 83.6, every base exactly on the kerb top.',
        src:['blender/city/layout.py','def tower_plots'] },
      { id:'inst', x:720, y:658, w:280, h:66, kind:'data', lab:'167 instances', sub:'asserted via depsgraph',
        t:'Scatter output', d:'A mis-wired Geometry Nodes graph fails silently and yields nothing, so this was asserted by evaluating the depsgraph and counting, not by a clean exit.',
        src:['blender/city/scatter.py','def _build_park_node_group'] },
      { id:'atmo', x:720, y:744, w:280, h:66, kind:'data', lab:'bounded domain', sub:'not a World volume',
        t:'Atmosphere box', d:'A World volume is unbounded: every sky-bound ray accumulates infinite optical depth and renders pure black. Measured 0.00033 mean against 0.968. No density fixes it; the medium needs a box.',
        src:['blender/city/lighting.py','def _build_atmosphere_domain'] },
      { id:'dev', x:720, y:916, w:280, h:66, kind:'data', lab:'device = GPU', sub:'METAL, 38 cores',
        t:'Chosen device', d:'Reported at runtime with backends and device names logged. Falls back to CPU cleanly.',
        src:['blender/city/render.py','def configure_device'] },

      { id:'ready', x:380, y:1030, w:250, h:60, kind:'stage', lab:'scene complete', sub:'three ways out',
        t:'Built scene', d:'Geometry, materials, lighting and camera all exist. What happens next is a branch.',
        src:['blender/build_city.py','def _run_stage'] },
      { id:'still', x:40, y:1140, w:250, h:66, kind:'stage', lab:'render.render()', sub:'Cycles path trace',
        t:'Render a still', d:'Path traces on the GPU. Usable at 96 samples only because OpenImageDenoise cleans up the rest.',
        src:['blender/city/render.py','def render(ctx)'] },
      { id:'gltf', x:380, y:1140, w:250, h:66, kind:'stage', lab:'--export-gltf', sub:'realise + export',
        t:'Export to glTF', d:'export_apply alone silently exports zero trees — it evaluates the Geometry Nodes modifier but leaves instances, which the exporter drops. export_gn_mesh realises them; verified by counting nodes, 192 to 359.',
        src:['blender/build_city.py','def _export_gltf'] },
      { id:'blend', x:720, y:1140, w:280, h:66, kind:'stage', lab:'--save-blend', sub:'the scene itself',
        t:'Save a .blend', d:'The one route that gives interactivity and path tracing at the same time.',
        src:['blender/build_city.py','save_as_mainfile'] },
      { id:'png', x:40, y:1252, w:250, h:60, kind:'out', lab:'renders/city_*.png', sub:'four presets',
        t:'The stills', d:'Verified non-blank by sampling mean pixel values — an early "success" was a 50 KB PNG that was entirely transparent.',
        src:['blender/city/render.py','def _output_path'] },
      { id:'glb', x:380, y:1252, w:250, h:60, kind:'out', lab:'renders/city_*.glb', sub:'~0.2 MB',
        t:'The exported scene', d:'359 nodes: towers, trees, terrain and bridges with PBR and emissive materials.',
        src:['blender/build_city.py','export_scene.gltf'] },
      { id:'bfile', x:720, y:1252, w:280, h:60, kind:'out', lab:'renders/city.blend', sub:'full scene',
        t:'The Blender file', d:'Everything the pipeline built, openable in the GUI.',
        src:['blender/build_city.py','save_as_mainfile'] },
      { id:'gal', x:40, y:1364, w:250, h:66, kind:'view', lab:'gallery.html', sub:'the stills',
        t:'Still gallery', d:'Where the light transport is actually visible — GI, real glass, volumetrics, windows that light the city.',
        src:['gallery.html','function render(demo)'] },
      { id:'view', x:380, y:1364, w:250, h:66, kind:'view', lab:'viewer.html', sub:'orbit · zoom · pan',
        t:'Interactive viewer', d:'three.js loading the exported scene. Interactivity back, light transport gone: emissive windows glow but illuminate nothing. Needs HTTP — file:// blocks the fetch.',
        src:['viewer.html','function prepare'] },
      { id:'gui', x:720, y:1364, w:280, h:66, kind:'view', lab:'Blender GUI', sub:'interactive path tracing',
        t:'The best of both', d:'Open the .blend, set the viewport to Rendered. Orbit with Cycles re-converging live on the GPU.',
        src:['docs/BLENDER.md','## Run it'] },
    ],
    edges: [
      {a:'shell',b:'blender',l:'provides',t:'nix-shell',d:'Puts this exact Blender on PATH; nothing downloads because the pin resolves to the store path already present.'},
      {a:'gc',b:'shell',dash:true,l:'protects',t:'Keeps the closure alive',d:'Not a build step — a safety line against garbage collection.'},
      {a:'blender',b:'gpu',l:'detects',t:'Runtime device query',d:'Backends are read from the Cycles addon preferences at run time, never assumed.'},
      {a:'cli',b:'entry',l:'args',t:'Parsed options',d:'Resolved into one preset dict so every stage reads from a single place.'},
      {a:'layout',b:'entry',l:'contract',t:'Constants and presets',d:'tower_plots() is called once; nothing downstream re-derives layout maths.'},
      {a:'entry',b:'mat',l:'stage 1',t:'First stage',d:'Materials run first because every later stage reads finished materials by name.'},
      {a:'mat',b:'terr',t:'Order matters',d:'Terrain reads asphalt, water, kerb, gravel and ground from the registry.'},
      {a:'terr',b:'bld',t:'Ground before towers',d:'Towers sit on the kerbed platforms terrain builds.'},
      {a:'bld',b:'scat',t:'City before planting',d:'Scatter distributes onto the park lawn, so that surface must exist.'},
      {a:'scat',b:'light',t:'Geometry before light',d:'Lighting sizes its atmosphere box around the finished scene.'},
      {a:'light',b:'cam',t:'Light before camera',d:'Both read the same preset; order here is convention rather than dependency.'},
      {a:'cam',b:'conf',t:'Scene before settings',d:'Render configuration comes last so it can inspect what was built.'},
      {a:'layout',b:'plots',dash:true,l:'resolves',t:'tower_plots(seed)',d:'Pure Python, no bpy — which is why it can be tested without Blender.'},
      {a:'plots',b:'bld',l:'consumed by',t:'Footprints in',d:'Every random choice derives from a per-plot seed, so each tower is reproducible and independent.'},
      {a:'scat',b:'inst',dash:true,l:'produces',t:'Instances out',d:'The count is the check. Success means non-zero instances, not a clean exit.'},
      {a:'light',b:'atmo',dash:true,l:'builds',t:'Bounded medium',d:'Density calibrated against the ~340-unit camera distance.'},
      {a:'conf',b:'dev',dash:true,l:'selects',t:'Device decision',d:'Logged loudly: this one choice is seconds versus minutes per frame.'},
      {a:'conf',b:'ready',t:'Ready',d:'Scene fully described. Nothing rendered yet.'},
      {a:'ready',b:'still',l:'default',t:'Render branch',d:'The default action; everything else is behind a flag.'},
      {a:'ready',b:'gltf',l:'flag',t:'Export branch',d:'Hides the atmosphere box first — it would otherwise export as an opaque cube around the city.'},
      {a:'ready',b:'blend',l:'flag',t:'Save branch',d:'A straight save; nothing lost.'},
      {a:'still',b:'png',t:'Writes PNG',d:'Colour managed through AgX with a glare pass so emissive windows bloom.'},
      {a:'gltf',b:'glb',t:'Writes GLB',d:'Geometry, PBR, emission and hierarchy survive. Volumetrics, real glass and GI do not.'},
      {a:'blend',b:'bfile',t:'Writes .blend',d:'Node graphs included, so procedural materials stay editable.'},
      {a:'png',b:'gal',t:'Displayed by',d:'A static page.'},
      {a:'glb',b:'view',t:'Loaded by',d:'Fetched by GLTFLoader, which needs HTTP.'},
      {a:'bfile',b:'gui',t:'Opened in',d:'Set viewport shading to Rendered for live Cycles.'},
    ],
  },
},

/* ----------------------------------------------------------------- CABIN -- */
{
  id: 'cabin',
  title: 'Spruce cabin at dusk',
  tagline: 'A Minecraft-style voxel valley, generated procedurally — no Minecraft, no Mineways, no MCprep. Warm windows, a glowing campfire, spruce silhouettes and evening fog.',
  run: 'blender --background --python blender/build_cabin.py -- --preset dusk',
  facts: [
    ['world', '96×96×48'], ['solid blocks', '95,911'], ['quads', '16,104'],
    ['mesh reduction', '123.7×'], ['render', '4–10 s'],
  ],
  stills: [
    { file: 'renders/cabin_dusk.png', name: 'dusk · 4° sun',
      what: 'The hero shot: cabin in a clearing, forest closing in, river beyond.',
      why: '<b>Why Cycles:</b> the lit windows and campfire are real emitters. The warm pool on the grass is light that actually travelled there, not a painted gradient.',
      alt: 'A voxel spruce cabin in a forest clearing at dusk, warm light in its windows, a campfire glowing beside it, blue river visible through the trees.' },
    { file: 'renders/cabin_night.png', name: 'night · sun below horizon',
      what: 'The fire and windows are the only meaningful light.',
      why: '<b>The clearest demonstration in either scene.</b> Cool moonlight gives the forest a silhouette; everything warm you can see is emitted by two block types and bounced.',
      alt: 'The same cabin at night under cool blue moonlight, windows glowing orange and a campfire casting a warm pool of light across the grass and cabin wall.' },
    { file: 'renders/cabin_snow.png', name: 'snow',
      what: 'The widest framing — the valley as a landscape.',
      why: 'Same geometry, different preset. Sun angle, fog density and camera all come from one declarative dict.',
      alt: 'Wide view of the voxel valley under bright cold light, cabin small in the middle distance surrounded by spruce forest.' },
    { file: 'renders/cabin_interior.png', name: 'interior',
      what: 'Inside the cabin, lit by its own lamps.',
      why: 'Proof the interior is genuinely hollow — a solid box would emit nothing and the whole warm-window concept would silently fail.',
      alt: 'Interior view inside the voxel cabin, plank walls and floor lit warmly by lamps, window openings glowing.' },
  ],
  viewer: {
    variants: [
      { label: 'Dusk',  file: 'renders/cabin_dusk.glb',  night: false },
      { label: 'Night', file: 'renders/cabin_night.glb', night: true  },
    ],
    home: { pos: [88, 8, 36], target: [45.5, 44.5, 12], zUp: true },
    sky: { day: { elev: 8, azim: 210 }, night: { elev: -5, azim: 210 } },
    note: 'The whole voxel world is a single mesh — the greedy mesher merged 95,911 blocks into 16,104 quads before export.',
  },
  pipeline: {
    nodes: [
      { id:'shell', x:40, y:36, w:250, h:70, kind:'env', lab:'shell.nix', sub:'same pinned nixpkgs',
        t:'Shared environment', d:'Identical to the city demo — one pinned Blender serves every scene. Adding a demo costs no new environment work.',
        src:['shell.nix','nixpkgs ? builtins.fetchTarball'] },
      { id:'blender', x:380, y:36, w:250, h:70, kind:'env', lab:'Blender 5.2.0 LTS', sub:'shared',
        t:'The renderer', d:'The same store path the city demo uses.', src:['shell.nix','pkgs.blender'] },
      { id:'gpu', x:720, y:36, w:280, h:70, kind:'env', lab:'Cycles · METAL', sub:'M2 Max, 38 GPU cores',
        t:'GPU path tracing', d:'Detected by the shared city/render.py — the cabin pipeline inherits Metal detection, denoising and AgX for free.',
        src:['blender/city/render.py','def configure_device'] },

      { id:'cli', x:40, y:262, w:250, h:76, kind:'code', lab:'CLI arguments', sub:'--preset --seed',
        t:'Command line', d:'Four presets: dusk, night, snow, interior. --no-render builds and stops.',
        src:['blender/build_cabin.py','def _parse_args'] },
      { id:'entry', x:380, y:262, w:250, h:76, kind:'code', lab:'build_cabin.py', sub:'stage order · ctx',
        t:'Orchestrator', d:'Same shape as build_city.py, and it REUSES city/camera.py and city/render.py rather than duplicating them. output_prefix on the ctx keeps cabin renders from overwriting the city\'s — they share a directory and the prefix was once hardcoded.',
        src:['blender/build_cabin.py','def main'] },
      { id:'layout', x:720, y:262, w:280, h:76, kind:'code', lab:'cabin/layout.py', sub:'the frozen contract',
        t:'Single source of truth', d:'Block enum, BLOCK_MATERIALS, world extents and the four presets. Native Blender Z-up throughout — deliberately unlike the city package, which carries a three.js Y-up legacy and remaps at every placement.',
        src:['blender/cabin/layout.py','BLOCK_SIZE'] },

      { id:'mat', x:380, y:400, w:250, h:66, kind:'stage', lab:'1 · materials', sub:'14 node graphs',
        t:'Materials', d:'All procedural, zero image files — no texture pack and no Minecraft atlas, which is the point. Coordinates come from Geometry > Position, not UVs, because greedy meshing merges a 20-block wall into one quad and any UV pattern would stretch across it.',
        src:['blender/cabin/materials.py','def build_materials'] },
      { id:'terr', x:380, y:486, w:250, h:66, kind:'stage', lab:'2 · terrain', sub:'ground · river · clearing',
        t:'Terrain', d:'Rolling heightmap, a meandering channel filled to one flat water level (a stepped surface would destroy the reflections), a levelled clearing and a winding path.',
        src:['blender/cabin/terrain.py','def build_terrain'] },
      { id:'cab', x:380, y:572, w:250, h:66, kind:'stage', lab:'3 · cabin', sub:'walls · roof · lamps',
        t:'The cabin', d:'Log-framed plank walls, stepped gable roof with overhang, glass on two sides, hearth and chimney, campfire outside. The interior must be genuinely hollow: verified interior_air=236.',
        src:['blender/cabin/cabin.py','def build_cabin'] },
      { id:'scat', x:380, y:658, w:250, h:66, kind:'stage', lab:'4 · scatter', sub:'161 spruce',
        t:'Forest', d:'Voxel writing, not Geometry Nodes — trees become part of the one world mesh. Refuses to grow off-grass, in the clearing, on the camera sight line, or within 16 units of the lens.',
        src:['blender/cabin/scatter.py','def build_scatter'] },
      { id:'mesh', x:380, y:744, w:250, h:66, kind:'stage', lab:'5 · build_mesh', sub:'cull + greedy merge',
        t:'The voxel mesher', d:'Naive cube-per-block is ~1M faces, nearly all buried inside solid rock. Hidden-face culling then greedy merging of coplanar runs gets 123.7× on real terrain. A solid 16³ cube meshes to exactly 6 quads — the strongest single test that both halves work.',
        src:['blender/cabin/blocks.py','def build_mesh'] },
      { id:'light', x:380, y:830, w:250, h:66, kind:'stage', lab:'6 · lighting', sub:'sky · fire · fog',
        t:'Lighting', d:'Physically-based sky, sun, bounded fog, and real point lights placed at every LAMP and CAMPFIRE block. The emissive materials already light the scene; the point lights just give Cycles something direct to sample so small emitters seen through glass are not noisy.',
        src:['blender/cabin/lighting.py','def build_lighting'] },
      { id:'cam', x:380, y:916, w:250, h:66, kind:'stage', lab:'7 · camera (shared)', sub:'city/camera.py',
        t:'Reused, not copied', d:'The city\'s camera module, unchanged. Framing, DOF and the turntable helper all work on any scene that supplies the same preset keys.',
        src:['blender/city/camera.py','def build_camera'] },

      { id:'vol', x:720, y:486, w:280, h:66, kind:'data', lab:'volume 96×96×48', sub:'uint8 numpy array',
        t:'The shared volume', d:'One array written by terrain, then cabin, then scatter, in that order — each reads what the last placed. Meshed exactly once, after all three.',
        src:['blender/cabin/blocks.py','def new_volume'] },
      { id:'hollow', x:720, y:572, w:280, h:66, kind:'data', lab:'interior_air = 236', sub:'asserted',
        t:'Genuinely hollow', d:'The single most important check in the scene. A solid cabin emits nothing through its windows and the entire lighting concept fails silently, with no error anywhere.',
        src:['blender/cabin/cabin.py','interior_air'] },
      { id:'quads', x:720, y:744, w:280, h:66, kind:'data', lab:'16,104 quads', sub:'from 95,911 blocks',
        t:'Mesher output', d:'Verified on varied terrain, not flat slabs — flat ground merges unrealistically well and reported a meaningless 36,948×.',
        src:['blender/cabin/blocks.py','def mesh_stats'] },
      { id:'lights', x:720, y:830, w:280, h:66, kind:'data', lab:'5 point lights', sub:'= 5 emissive blocks',
        t:'Emitter sampling', d:'Count asserted against the emissive block count. Night was once a black frame with four lit rectangles floating in it — the emitters were visible but lit nothing until strengths were raised and moonlight added.',
        src:['blender/cabin/lighting.py','def _block_lights'] },

      { id:'ready', x:380, y:1030, w:250, h:60, kind:'stage', lab:'scene complete', sub:'three ways out',
        t:'Built scene', d:'Same branch point as the city pipeline.', src:['blender/build_cabin.py','def _run_stage'] },
      { id:'still', x:40, y:1140, w:250, h:66, kind:'stage', lab:'render.render()', sub:'shared city/render.py',
        t:'Render a still', d:'The city\'s render module, reused unchanged.', src:['blender/city/render.py','def render(ctx)'] },
      { id:'gltf', x:380, y:1140, w:250, h:66, kind:'stage', lab:'--export-gltf', sub:'hides the fog box',
        t:'Export to glTF', d:'The fog domain is a Cycles-only construct with no surface shader. Exporting it would wrap the valley in an opaque cube — and the name it checks for was once stale, which fails silently by exporting the box.',
        src:['blender/build_cabin.py','def _export_gltf'] },
      { id:'blend', x:720, y:1140, w:280, h:66, kind:'stage', lab:'--save-blend', sub:'the scene itself',
        t:'Save a .blend', d:'Interactivity and path tracing together.', src:['blender/build_cabin.py','save_as_mainfile'] },

      { id:'png', x:40, y:1252, w:250, h:60, kind:'out', lab:'renders/cabin_*.png', sub:'four presets',
        t:'The stills', d:'Namespaced by output_prefix so they cannot collide with the city\'s renders in the same directory.',
        src:['blender/city/render.py','def _output_path'] },
      { id:'glb', x:380, y:1252, w:250, h:60, kind:'out', lab:'renders/cabin_*.glb', sub:'1.8 MB',
        t:'The exported scene', d:'One mesh, 13 materials, emissive lamp and campfire preserved.',
        src:['blender/build_cabin.py','export_scene.gltf'] },
      { id:'bfile', x:720, y:1252, w:280, h:60, kind:'out', lab:'renders/cabin.blend', sub:'full scene',
        t:'The Blender file', d:'Openable in the GUI with everything intact.', src:['blender/build_cabin.py','save_as_mainfile'] },

      { id:'gal', x:40, y:1364, w:250, h:66, kind:'view', lab:'gallery.html', sub:'the stills',
        t:'Still gallery', d:'Where the light transport shows.', src:['gallery.html','function render(demo)'] },
      { id:'view', x:380, y:1364, w:250, h:66, kind:'view', lab:'viewer.html', sub:'orbit · zoom · pan',
        t:'Interactive viewer', d:'Interactivity back, light transport gone — the campfire glows but warms nothing.',
        src:['viewer.html','function prepare'] },
      { id:'gui', x:720, y:1364, w:280, h:66, kind:'view', lab:'Blender GUI', sub:'interactive path tracing',
        t:'The best of both', d:'blender --python blender/build_cabin.py -- --preset dusk --no-render opens straight into a Rendered viewport.',
        src:['blender/build_cabin.py','def _setup_gui_viewport'] },
    ],
    edges: [
      {a:'shell',b:'blender',l:'provides',t:'nix-shell',d:'Same pinned closure as the city demo.'},
      {a:'blender',b:'gpu',l:'detects',t:'Runtime device query',d:'Via the shared render module.'},
      {a:'cli',b:'entry',l:'args',t:'Parsed options',d:'Resolved into one preset dict.'},
      {a:'layout',b:'entry',l:'contract',t:'Voxel constants',d:'Block palette, world extents and presets — importable without bpy.'},
      {a:'entry',b:'mat',l:'stage 1',t:'First stage',d:'Materials first; the mesher looks them up by key when assigning face slots.'},
      {a:'mat',b:'terr',t:'Materials before geometry',d:'build_mesh maps block ids to material keys, so the registry must exist.'},
      {a:'terr',b:'cab',t:'Ground before building',d:'The cabin needs the levelled clearing terrain produced.'},
      {a:'cab',b:'scat',t:'Building before forest',d:'Scatter reads the volume to avoid growing trees through the roof.'},
      {a:'scat',b:'mesh',t:'All blocks placed',d:'Meshing happens exactly once, after every volume-writing stage.'},
      {a:'mesh',b:'light',t:'Geometry before light',d:'Lighting scans the volume for emissive blocks and sizes the fog box around the world.'},
      {a:'light',b:'cam',t:'Light before camera',d:'Both read the same preset.'},
      {a:'terr',b:'vol',dash:true,l:'writes',t:'Shared array',d:'Terrain writes first; cabin and scatter write into the same array.'},
      {a:'cab',b:'hollow',dash:true,l:'asserted',t:'Hollow check',d:'Counted directly inside the wall envelope, not inferred.'},
      {a:'mesh',b:'quads',dash:true,l:'produces',t:'Quad count',d:'Reported every build so a regression in the mesher is visible immediately.'},
      {a:'light',b:'lights',dash:true,l:'places',t:'Point lights',d:'One per emissive block, matched by count.'},
      {a:'cam',b:'ready',t:'Ready',d:'Scene fully described.'},
      {a:'ready',b:'still',l:'default',t:'Render branch',d:'The default action.'},
      {a:'ready',b:'gltf',l:'flag',t:'Export branch',d:'Fog box hidden first.'},
      {a:'ready',b:'blend',l:'flag',t:'Save branch',d:'A straight save.'},
      {a:'still',b:'png',t:'Writes PNG',d:'Prefixed cabin_ so it cannot overwrite the city.'},
      {a:'gltf',b:'glb',t:'Writes GLB',d:'One mesh; emission survives, volumetrics do not.'},
      {a:'blend',b:'bfile',t:'Writes .blend',d:'Everything intact.'},
      {a:'png',b:'gal',t:'Displayed by',d:'Static page.'},
      {a:'glb',b:'view',t:'Loaded by',d:'Needs HTTP.'},
      {a:'bfile',b:'gui',t:'Opened in',d:'Or launch the pipeline directly with a UI.'},
    ],
  },
},

];
